[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[tools]
age = "latest"
bun = "latest"
carapace = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
gum = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
sops = "latest"
starship = "latest"
tree-sitter = "latest"
yazi = "latest"
zellij = "latest"

# linux-specific
"ubi:nushell/nushell" = { version = "latest", os = ["linux"], extract_all = true }

